### 386.4.4 R-GLAB Aggregate Functions

In [1]:
import pandas as pd

In [2]:
data = {
    'Category': ['A', 'A', 'B', 'B', 'A', 'B'],
    'Value': [10, 15, 20, 25, 30, 35],
    'Fee' :[20000,25000,26000,22000,24000,35000],
    'Duration':['30day','40days','35days','40days','60days','60days'],
    'Discount':[1000,2300,1200,2500,2000,2000]
}

df = pd.DataFrame(data)

In [3]:
df.head(6)

  Category  Value    Fee Duration  Discount
0        A     10  20000    30day      1000
1        A     15  25000   40days      2300
2        B     20  26000   35days      1200
3        B     25  22000   40days      2500
4        A     30  24000   60days      2000
5        B     35  35000   60days      2000

In [4]:
total_sum =df['Value'].aggregate('sum')
print('Total Sum:', total_sum)

total_sum2 = df['Value'].sum()
print(f'Total Sum: {total_sum2}')

Total Sum: 135
Total Sum: 135

In [5]:
# Cumulative Sum (Running Total)
df[['Value']].cumsum()

   Value
0     10
1     25
2     45
3     70
4    100
5    135

In [7]:
total_mean = df['Value'].aggregate('mean')
print(f'Total mean: {total_mean}')

mean = df['Value'].mean()
print(f'Mean: {mean}')

Total mean: 22.5
Mean: 22.5

In [8]:
max_val = df['Value'].agg('max')
print(f'Max Value: {max_val}')

max = df['Value'].max()
print(f'Max Value: {max}')

Max Value: 35
Max Value: 35

In [9]:
count = df['Value'].agg('count')
print(f'Count: {count}')

count1 = df['Value'].count()
print(f'Count: {count1}')

Count: 6
Count: 6

In [10]:
std = df['Value'].agg('std')
print(f'Standard Dev: {std}')

std1 = std = df['Value'].std()
print(f'Standard Dev: {std1}')

Standard Dev: 9.354143466934854
Standard Dev: 9.354143466934854

## Apply Multiple Aggregation Functions

* 'df[] - grabbing a series from a df - single column
* 'df[[]] - grabbing a dataframe from a df - multicolumn

In [11]:
result = df[['Fee', 'Discount']].aggregate('sum')

print(result)

result2 = df[['Fee', 'Discount']].sum()
result2

Fee         152000
Discount     11000
dtype: int64

Fee         152000
Discount     11000
dtype: int64

In [12]:
# Determine the total of eachg group with and agg function
result_group = df.groupby('Category')[['Fee', 'Discount']].agg('sum')

print(result_group)

            Fee  Discount
Category
A         69000      5300
B         83000      5700